### PR TITLE
Add fix for node intergration warning

### LINKED ISSUE #69: Fix electron security warnings
Three security warnings are present during development, work needs to be done to resolve these.

### PR DESCRIPTION
**Pull request by joshxg**
fixes #69 

Three warnings were present

1. Node integration - FIXED
1. Content-security-policy header - Unchanged
1. Unsafe content - Unchanged

To resolve the CSP warning of (2),  content-security-policy headers can be set. However as we serve bundled content with the use of eval(), another warning would be present - use of unsafe eval.

To resolve the warning of (3), unsafe content, the web-dev-server serving content in development mode must use HTTPS rather than HTTP. To resolve this warning either web-dev-server can generate self-signed certificates - this requires developers to enable self-signed certificates. Or, each developer could create their own certificates (from what I understand). This seems excessive to fix a very minor warning message present during development mode.

Please let me know if I have understood anything incorrectly.

(Also changed the dimensions of the electron window on load, while I was in main.js)

### CODE REVIEW

**Comment by wlthomson** [comment]
Looks good. I think in terms of security, it may be be a good idea to do a proper audit after beta is released. Quick question before I merge, would this cause any problems for starting and stopping the server in react code being rendered in the electron window?

**Comment by joshxg** [comment]
It is a good idea - as we are only serving our local HTML in production, we shouldn't have to many issues. The electron recommendations can be seen here - https://electronjs.org/docs/tutorial/security

This will only stop the renderer process from using node. Primarily for XSS attacks - more here: https://electronjs.org/docs/tutorial/security#2-disable-nodejs-integration-for-remote-content 

If we happen to need node within the renderer process (maybe to read a settings file for instance), we can preload the dependency with the 'preload' option.

Really, as we aren't navigating anywhere other than local content, this isn't strictly necessary, but the warning message was annoying..

**Comment by wlthomson** [comment]
No worries, according to the design principles we discussed, the renderer process should just be as a "dumb" UI anyway, so perhaps the main process could pass a function down to the renderer (a la react) or we could just add a bit of IPC. Does that sound about right?

**Comment by joshxg** [comment]
Sounds good. Although I really don't think we will need it. Conflicts are resolved now also.

**Comment by wlthomson** [comment]
Looks good. Merging and deleting branch.

**Pull request closed without merging**
