### PR TITLE
#160 fix missing supplierNameId from PUT and POST requisitions

### LINKED ISSUE #160: API: SQLite error on requisition endpoint - put
Server logs an error on when a put request is sent to the requisitions endpoint

{ SQLError: SQL query UPDATE requisition
[2]                  SET supplierNameId = "undefined",
[2]                      date = "2019-01-23T11:00:00.000Z",
[2]                      status = "fn",
[2]                      type = "request",
[2]                      orderType = "regular",
[2]                      daysToSupply = 30,
[2]                      comment = "aaaaaa",
[2]                      enteredBy = "undefined",
[2]                      serialNo = 0d3ff200-1f75-11e9-b028-155484c2ffae,
[2]                      requesterReference = ""
[2]                  WHERE id = "0d3ff200-1f75-11e9-b028-155484c2ffae" threw error Error: SQLITE_ERROR: unrecognized token: "0d3ff200".

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #160. 

Can't test requisition creation on current dev machine. Tested using Postman replicating current axios setup.

### CODE REVIEW

**Comment by joshxg** [comment]
This has fixed what it says, however there still seems to be a bug for putting and posting requisitions: ID's given by the server in the form xxxx-xxxx-xxxx cause SQLite errors. Not sure if it should be fixed in this PR, as putting and posting is still currently broken or if a new issue should be opened, let me know.

**Comment by wlthomson** [comment]
Just tested with a fresh `yarn clean` and all the endpoints are working for me. The UID needs to be changed (for consistency), but SQLite should be fine with it (it's just entered as a string).

**Comment by wlthomson** [comment]
There seems to be a bit of funny business with the `serialNo` being defined as an integer. If that is the only issue, this will most likely have been fixed in #132. Since there are a few outstanding PRs which work on server logic. It will probably be best to merge then and then make an issue for any remaining bugs. Most should be resolved by theremaining PRs, though.

**Comment by wlthomson** [comment]
As discussed, going ahead and merging.

**Pull request merged**
